
FROM     debian:7
MAINTAINER Romain "lahaxe@unistra.fr"

RUN echo "deb http://ftp.u-strasbg.fr/debian/ wheezy-backports main" >> /etc/apt/sources.list && \
    apt-get -qq -y update && \
    apt-get -qq -y install debconf-utils build-essential binutils-doc \
                           autoconf flex bison cmake scons wget git \
                           mercurial subversion gzip bzip2 zip unzip \
                           openssh-server openjdk-7-jdk sudo lsb-release

RUN mkdir /var/run/sshd && useradd "jenkins" && \
    echo "jenkins:jenkins" | chpasswd && mkdir "/home/jenkins" && \
    chown "jenkins:jenkins" "/home/jenkins" && chmod a+w "/home/jenkins" && \
    echo "jenkins ALL=NOPASSWD: ALL" >> /etc/sudoers

RUN /usr/sbin/sshd
