
FROM     ubuntu:trusty
MAINTAINER Romain "lahaxe@unistra.fr"

RUN apt-get -qq -y update && \
    apt-get -qq -y install cmake aptitude make swig2.0 libdcmtk2-dev \
                           g++ dcmtk libmimetic-dev libmongo-client-dev \
                           mongodb-dev libcgicc5-dev python-nose libqt4-dev \
                           libboost-all-dev liblog4cpp5-dev mongodb\
                           libldap2-dev libssl-dev libwrap0-dev wget bzip2 git \
                           openssh-server openjdk-7-jdk

RUN rm -rf /data && mkdir data && mkdir /data/db && mkdir /var/run/sshd && \
    chmod a+rw /data && chmod a+rw /data/db && \
    useradd "jenkins" && echo "jenkins:jenkins" | chpasswd && mkdir "/home/jenkins" && \
    chown "jenkins:jenkins" "/home/jenkins" && chmod a+w "/home/jenkins"

RUN /usr/sbin/sshd
